spring:
  application:
    name: Restro-App

  datasource:
    #jdbc:db://host:port/DbName
    url: jdbc:postgresql://localhost:5435/postgres
    username: appOwner
    password: appowner@2003
    driverClassName: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none

  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:db.changelog/restaurant-master-changelog.xml
    default-schema: dummy

test:
  property:
    dummy: ABC